- name: Install snapd if not already present
  dnf:
    name: snapd
    state: present

- name: Install snap collection
  community.general.ansible_galaxy_install:
    name: community.general
    type: collection

- name: Snapd symoblic link
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link

- name: Start the snap service
  systemd:
    name: snapd
    enabled: true
    state: started

- name: Install Certbot
  community.general.snap:
    name: certbot
    classic: true
    state: present

- name: Install pip3
  dnf:
    name: pip3
    state: present

- name: Install certbot python package
  ansible.builtin.pip:
    name: certbot-dns-route53

- name: Certbot symoblic link
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    owner: root
    group: root
    state: link

- name: Request Let's Encrypt certificate
  command: certbot certonly --agree-tos --email {{ acme_email }} --dns-route53 -d {{ acme_domain }} -d www.{{ acme_domain }}
  register: certbot_output

- name: Print certbot output
  debug:
    mag: "{{ certbot_output }}"