- name: Install snapd if not already present
  dnf:
    name: snapd
    state: present

- name: Install snap collection
  community.general.ansible_galaxy_install:
    name: community.general
    type: collection

- name: Snapd symoblic link
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link

- name: Start the snap service
  systemd:
    name: snapd
    enabled: true
    state: started

- name: Install Certbot
  community.general.snap:
    name: certbot
    classic: true
    options: trust-plugin-with-root=ok
    state: present

- name: Install pip
  dnf:
    name: pip
    state: present

- name: Certbot symoblic link
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    owner: root
    group: root
    state: link

- name: Install Certbot Route53 DNS plugin
  community.general.snap:
    name: certbot-dns-route53
    classic: true
    options: trust-plugin-with-root=ok
    state: present

- name: Request Let's Encrypt certificate
  command: certbot certonly --agree-tos -m {{ acme_email }} --dns-route53 -d {{ acme_domain }} -d www.{{ acme_domain }}
  register: certbot_output
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"

- name: Print certbot output
  debug:
    mag: "{{ certbot_output }}"