- name: Install podman if not already present
  package:
    name: podman
    state: present

- name: Install containers.podman collection
  community.general.ansible_galaxy_install:
    name: containers.podman
    type: collection

- name: Start PostgreSQL container
  containers.podman.podman_container:
    name: postgres
    image: docker.io/library/postgres
    ports:
      - "5432:5432"
    env:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    state: started