- name: Install podman if not already present
  dnf:
    name: podman
    state: present

- name: Install containers.podman collection
  community.general.ansible_galaxy_install:
    name: containers.podman
    type: collection

- name: Start PostgreSQL container
  containers.podman.podman_container:
    name: postgres
    image: docker.io/library/postgres
    ports:
      - "5432:5432"
    env:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    state: started

- name: Ensure a job that runs weekly to backup Postgres. Creates an entry like "0 1 * * *"
  ansible.builtin.cron:
    name: "backup postgres"
    minute: "0"
    hour: "1"
    job: "docker exec -i postgres /usr/bin/pg_dump -U postgres postgres | gzip -9 > $(date +'%Y-%m-%d')_postgres-backup.sql.gz l"