---
- name: Install RPM packages
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Include group vars
      include_vars:
        file: group_vars/all.yml

    - name: Rhel 9 STIG
      include_role:
        name: rhel9STIG

    - name: Update sshd_config to allow password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
      notify: Restart SSH

    - name: Add iptables rule to forward traffic
      iptables:
        chain: PREROUTING
        table: nat
        protocol: tcp
        dport: 8200
        jump: REDIRECT
        to_ports: 8200

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
