---
- name: Install RPM packages
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Include group vars
      include_vars:
        file: group_vars/all.yml

    - name: Run RHEL 9 STIG
      command: rhel9STIG-ansible/enforce.sh
      args:
        creates: rhel9STIG-ansible/indicator_file.txt
      register: script_result
      ignore_errors: yes  # Ignore errors to check return code

    - name: Handle script result
      debug:
        msg: "Script executed successfully"
      when: script_result.rc == 0  # Check if return code is 0
