---
- name: Install RPM packages
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Include group vars
      include_vars:
        file: group_vars/all.yml

    - name: Rhel 9 STIG
      include_role:
        name: rhel9STIG

    - name: Handle script result
      debug:
        msg: "Script executed successfully"
      when: script_result.rc == 0  # Check if return code is 0
