---
- name: Install RPM packages
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Include group vars
      include_vars:
        file: group_vars/all.yml

    - name: Rhel 9 STIG
      include_role:
        name: rhel9STIG
