---
- name: Install RPM packages
  hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: Include group vars
      include_vars:
        file: group_vars/all.yml

    - name: Rhel 9 STIG
      include_role:
        name: rhel9STIG

    - name: Update sshd_config to allow password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
      notify: Restart SSH

    - name: Add iptables rule to forward traffic on all defined ports
      block:
        - name: Allow inbound traffic on all defined ports
          iptables:
            chain: INPUT
            protocol: tcp
            destination_port: "{{ item }}"
            jump: ACCEPT
          loop: "{{ input_ports }}"

        - name: Allow outbound traffic on all defined ports
          iptables:
            chain: OUTPUT
            protocol: tcp
            destination_port: "{{ item }}"
            jump: ACCEPT
          loop: "{{ output_ports }}"
      
  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
