- name: Let's encrypt Ansible ACME example
  hosts: localhost
  become: true

  tasks:
    - name: Include group vars
      include_vars:
        file: group_vars/all.yml
        
    - name: Install snapd if not already present
      package:
        name: snapd
        enabled: true
        state: present

    - name: Install containers.podman collection
      community.general.ansible_galaxy_install:
        name: snap
        type: collection

    - name: Snapd symoblic link
      file:
        src: /var/lib/snapd/snap
        dest: /snap
        owner: root
        group: root
        state: link

    - name: Install foo
      community.general.snap:
        name: certbot
        classic: true
        state: present

    - name: Snapd symoblic link
      file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        owner: root
        group: root
        state: link

    - name:
      command: certbot certonly --dns-route53 -d {{ acme_domain }} -d www.{{ acme_domain }}

