---
- name: Deploy Vault
  hosts: localhost
  become: yes
  tasks:
    - name: Install yum-utils
      dnf:
        name: yum-utils
        state: latest

    - name: Add official HashiCorp Linux repository.
      command: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

    - name: Install Vault
      dnf:
        name: vault
        state: latest